blank_issues_enabled: true
contact_links:
- name: Monkestation Discord Server
  url: https://discord.monkestation.com
  about: For help with running the game, or joining the server, join our Discord server.
